export enum DbEnums {
  NPC_TABLE = 'npc',
  NPC_COLUMN_ID = 'id',
  NPC_COLUMN_BLOB = 'blob',
  NPC_COLUMN_GENDER = 'gender',
  NPC_COLUMN_CLASS = 'class',
  NPC_COLUMN_AGE = 'age',
  NPC_COLUMN_RACE = 'race',
  NPC_COLUMN_CULTURE = 'culture',
  NPC_COLUMN_UPLOADER_ID = 'uploaderId',
  NPC_COLUMN_CREATED_BY_ID = 'createdById',
  NPC_COLUMN_MODIFIED_BY_ID = 'modifiedById',
  NPC_COLUMN_CREATED_AT = 'createdAt',
  NPC_COLUMN_MODIFIED_AT = 'modifiedAt',

  AVATAR_TABLE = 'avatar',
  AVATAR_COLUMN_ID = 'id',
  AVATAR_COLUMN_BLOB = 'blob',
  AVATAR_COLUMN_CREATED_AT = 'createdAt',
  AVATAR_COLUMN_UPLOADER_ID = 'uploaderId',

  USER_TABLE = 'user',
  USER_COLUMN_ID = 'id',
  USER_COLUMN_USERNAME = 'username',
  USER_COLUMN_EMAIL = 'email',
  USER_COLUMN_PASSWORD = 'password',
  USER_COLUMN_AVATAR_ID = 'avatarId',
  USER_COLUMN_ISACTIVE = 'isActive',

  NOTE_TABLE = 'note',
  NOTE_COLUMN_ID = 'id',
  NOTE_COLUMN_NPC_ID = 'npcId',
  NOTE_COLUMN_NAME = 'name',
  NOTE_COLUMN_DESCRIPTION = 'description',
  NOTE_COLUMN_CREATED_BY_ID = 'createdById',
  NOTE_COLUMN_MODIFIED_BY_ID = 'modifiedById',
  NOTE_COLUMN_CREATED_AT = 'createdAt',
  NOTE_COLUMN_MODIFIED_AT = 'modifiedAt',
}
