version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nestjs
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:
    driver: bridge

volumes:
  pgdata:
